### ISSUE TITLE
versioning is incorrect and pypi unsynced

### ISSUE THREAD

**Issue by theelous3** [defnull/multipart#14]
The version on pypi is listed as 0.1, but is identical to the version in master which is also 0.1, even though the code differs.

I haven't diffed them with a fine tooth comb or anything, but off the bat the raw property isn't available on `MultipartPart`s.

**Comment by defnull** [comment]
The version string of the `master` branch is irrelevant. Tags mark the exact release commit.

You can bump the version to `0.2-dev` or whatever is clearly recognizable as a non-release version in your next pull request, if you really want to.
