### ISSUE TITLE
Documentation / example for `cgi.FiledStorage` in `multipart`

### ISSUE THREAD

**Issue by albert-github** [defnull/multipart#50]
In the readme file of this project it is stated:
> Fixes many shortcomings and bugs of cgi.FieldStorage.

though I cannot find documentation for this and as:
> DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13

I think we should use multipart as well in the addon for doxygen: https://github.com/doxygen/doxygen/blob/master/addon/doxypysql/search.py#L294

The relevant code, as far as I can see:
```
def serveCgi():
    import cgi

    print('Content-Type: application/json\n')

    fieldStorage = cgi.FieldStorage()
    form = dict((key, fieldStorage.getvalue(key)) for key in fieldStorage.keys())

    if 'href' in form:
        ref = form['href']
    else:
        print('{"result": null, "error": "no refid given"}')
        sys.exit(0)

    cn=openDb('doxygen_sqlite3.db')

    j = processHref(cn,ref)

    print(json.dumps({"result":j,"error":None}))
```

and especially:
```
    import cgi
```
which should probably be:
```
    import multipart
```

and
```
    fieldStorage = cgi.FieldStorage()
    form = dict((key, fieldStorage.getvalue(key)) for key in fieldStorage.keys())
```

- where can I find the documentation?
- where can I find an example?

Maybe this is not the right place to ask, in that case please refer me to the place where to ask.

**Comment by defnull** [comment]
Have a look at the `parse_form_data()` function here: https://github.com/defnull/multipart/blob/master/multipart.py#L465
It shows how to parse form data (both `multipart/form-data` and `application/x-www-form-urlencoded`) from a WSGI environment. CGI is very similar, but also different. There is no ready to use function for CGI, you'd have to come up with that yourself. I is possible to build a WSGI environ dictionary from a CGI environment though, that might be the easiest solution for CGI apps.

Just a quick sketch, not actually tested:
```py
  environ = dict(os.environ.items())
  environ['wsgi.input'] = sys.stdin
  files, forms = multipart.parse_form_data(environ)
```

**Comment by amk1969** [comment]
A working script sample. Form parameters end up in a dictionary of lists, files as MultiDict.

```python
import os
import sys
import urllib.parse
from multipart import parse_form_data, MultiDict

environ = dict(os.environ.items())
environ['wsgi.input'] = sys.stdin.buffer

request_method = environ.get("REQUEST_METHOD").upper()
if request_method in ("POST", "PUT"):
    form, files = parse_form_data(environ)
    form = form.dict
elif request_method == "GET":
    form = urllib.parse.parse_qs(environ['QUERY_STRING'])
    files = MultiDict()
else:
    raise Exception('Method not supported')

print ('Content-type: text/plain\n\n')
for k,v in form.items():
    print(f"{k:20} = {v}")
```
