### ISSUE TITLE
Attempting to read more data is specified by Content-Length

### ISSUE THREAD

**Issue by jun66j5** [defnull/multipart#58]
WSGI specification says:

> The server is not required to read past the client’s specified Content-Length, and should simulate an end-of-file condition if the application attempts to read past that point. _**The application should not attempt to read more data than is specified by the CONTENT_LENGTH variable**_.

[Input and Error Streams | PEP 3333 – Python Web Server Gateway Interface v1.0.1 | peps.python.org](https://peps.python.org/pep-3333/#input-and-error-streams)

However, the multipart module attempts to read more data that is specified by Content-Length while parsing form-data since multipart 1.0.0 (for urlencoded-data before this version also).

(Originally reported at https://trac.edgewall.org/ticket/13789)

**Comment by defnull** [comment]
I have a fix ready and will probably push a patch release next week. Thanks for your very helpful reports so far!

**Comment by jun66j5** [comment]
Verified the issue being fixed with multipart 1.1.0. Thanks.
